const cities = [
  "Abbottabad",
  "Abdul Hakim",
  "Ahmadpur East",
  "Aliabad",
  "Alpurai",
  "Athmuqam",
  "Attock City",
  "Attock Khurd",
  "Awaran",
  "Badin",
  "Bagh",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Barkhan",
  "Batgram",
  "Bhakkar",
  "Bhalwal",
  "Chakwal",
  "Chaman",
  "Charsadda",
  "Chenab Nagar",
  "Chilas",
  "Chiniot",
  "Chishtian",
  "Chitral",
  "Chunian",
  "Dadu",
  "Daggar",
  "Dainyor",
  "Dalbandin",
  "Dasu",
  "Dera Allahyar",
  "Dera Bugti",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Dera Murad Jamali",
  "Dipalpur",
  "Eidgah",
  "Faisalabad",
  "Gakuch",
  "Gandava",
  "Ghotki",
  "Gilgit",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hafizabad",
  "Hangu",
  "Haripur",
  "Harunabad",
  "Hasilpur",
  "Hassan Abdal",
  "Hujra Shah Muqim",
  "Hyderabad City",
  "Islamabad",
  "Jacobabad",
  "Jalalpur Jattan",
  "Jamshoro",
  "Jaranwala",
  "Jhang City",
  "Jhelum",
  "Kabirwala",
  "Kahror Pakka",
  "Kalat",
  "Kamalia",
  "Kandhkot",
  "Karachi",
  "Karak",
  "Kasur",
  "Khairpur Mirâ€™s",
  "Khanewal",
  "Khanpur",
  "Kharan",
  "Kharian",
  "Khushab",
  "Khuzdar",
  "Khuzdar",
  "Kohat",
  "Kohlu",
  "Kot Addu",
  "Kotli",
  "Kulachi",
  "Kundian",
  "Lahore",
  "Lakki",
  "Lala Musa",
  "Larkana",
  "Leiah",
  "Lodhran",
  "Loralai",
  "Malakand",
  "Mandi Bahauddin",
  "Mandi Burewala",
  "Mansehra",
  "Mardan",
  "Mastung",
  "Matiari",
  "Mian Channun",
  "Mianwali",
  "Mingaora",
  "Mirpur Khas",
  "Multan",
  "Muridke",
  "Musa Khel Bazar",
  "Muzaffarabad",
  "Muzaffargarh",
  "Nankana Sahib",
  "Narowal",
  "Naushahro Firoz",
  "Nawabshah",
  "New Mirpur",
  "Nowshera",
  "Okara",
  "Pakpattan",
  "Panjgur",
  "Parachinar",
  "Pasrur",
  "Pattoki",
  "Peshawar",
  "Pishin",
  "Qila Saifullah",
  "Quetta",
  "Rahimyar Khan",
  "Rajanpur",
  "Rawala Kot",
  "Rawalpindi",
  "Risalpur Cantonment",
  "Saddiqabad",
  "Sahiwal",
  "Saidu Sharif",
  "Sambrial",
  "Samundri",
  "Sanghar",
  "Sargodha",
  "Shahdad Kot",
  "Shakargarh",
  "Shekhupura",
  "Shikarpur",
  "Shujaabad",
  "Sialkot City",
  "Sibi",
  "Sukkur",
  "Swabi",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Tank",
  "Thatta",
  "Timargara",
  "Toba Tek Singh",
  "Turbat",
  "Umarkot",
  "Upper Dir",
  "Uthal",
  "Vihari",
  "Zhob",
  "Ziarat",
  "Other",
];

const provinces = [
  "Gilgit Baltistan",
  "Balochistan",
  "Sindh",
  "Punjab",
  "KPK",
  "AJK",
  "Islamabad",
];

const countries = ["Pakistan"];

const education_levels = [
  "None",
  "Grade 8",
  "Matric/O Levels",
  "Inter/A Levels",
  "Bachelors",
  "Masters",
  "MPhil",
  "PhD",
];

const sources_of_information = [
  "Social Media",
  "IEC Student",
  "IEC Team Member",
  "Word of Mouth",
  "Email",
  "SMS",
  "Other",
];

const type_of_employment = ["Part Time", "Full Time", "Not Employed"];

const age_groups = ["Under 18", "18-21", "22-24", "25-26", "27-30", "Above 30"];

const genders = ["male", "female", "other"];
