"use strict";

var cities = ["Abbottabad", "Abdul Hakim", "Ahmadpur East", "Aliabad", "Alpurai", "Athmuqam", "Attock City", "Attock Khurd", "Awaran", "Badin", "Bagh", "Bahawalnagar", "Bahawalpur", "Bannu", "Barkhan", "Batgram", "Bhakkar", "Bhalwal", "Chakwal", "Chaman", "Charsadda", "Chenab Nagar", "Chilas", "Chiniot", "Chishtian", "Chitral", "Chunian", "Dadu", "Daggar", "Dainyor", "Dalbandin", "Dasu", "Dera Allahyar", "Dera Bugti", "Dera Ghazi Khan", "Dera Ismail Khan", "Dera Murad Jamali", "Dipalpur", "Eidgah", "Faisalabad", "Gakuch", "Gandava", "Ghotki", "Gilgit", "Gojra", "Gujranwala", "Gujrat", "Gwadar", "Hafizabad", "Hangu", "Haripur", "Harunabad", "Hasilpur", "Hassan Abdal", "Hujra Shah Muqim", "Hyderabad City", "Islamabad", "Jacobabad", "Jalalpur Jattan", "Jamshoro", "Jaranwala", "Jhang City", "Jhelum", "Kabirwala", "Kahror Pakka", "Kalat", "Kamalia", "Kandhkot", "Karachi", "Karak", "Kasur", "Khairpur Mirâ€™s", "Khanewal", "Khanpur", "Kharan", "Kharian", "Khushab", "Khuzdar", "Khuzdar", "Kohat", "Kohlu", "Kot Addu", "Kotli", "Kulachi", "Kundian", "Lahore", "Lakki", "Lala Musa", "Larkana", "Leiah", "Lodhran", "Loralai", "Malakand", "Mandi Bahauddin", "Mandi Burewala", "Mansehra", "Mardan", "Mastung", "Matiari", "Mian Channun", "Mianwali", "Mingaora", "Mirpur Khas", "Multan", "Muridke", "Musa Khel Bazar", "Muzaffarabad", "Muzaffargarh", "Nankana Sahib", "Narowal", "Naushahro Firoz", "Nawabshah", "New Mirpur", "Nowshera", "Okara", "Pakpattan", "Panjgur", "Parachinar", "Pasrur", "Pattoki", "Peshawar", "Pishin", "Qila Saifullah", "Quetta", "Rahimyar Khan", "Rajanpur", "Rawala Kot", "Rawalpindi", "Risalpur Cantonment", "Saddiqabad", "Sahiwal", "Saidu Sharif", "Sambrial", "Samundri", "Sanghar", "Sargodha", "Shahdad Kot", "Shakargarh", "Shekhupura", "Shikarpur", "Shujaabad", "Sialkot City", "Sibi", "Sukkur", "Swabi", "Tando Allahyar", "Tando Muhammad Khan", "Tank", "Thatta", "Timargara", "Toba Tek Singh", "Turbat", "Umarkot", "Upper Dir", "Uthal", "Vihari", "Zhob", "Ziarat", "Other"];
var provinces = ["Gilgit Baltistan", "Balochistan", "Sindh", "Punjab", "KPK", "AJK", "Islamabad"];
var countries = ["Pakistan"];
var education_levels = ["None", "Matric/O Levels", "Inter/A Levels", "Bachelors (2 years)", "Bachelors (4 years)", "Diploma after Matric/O Levels", "Diploma after Inter/A Levels", "Masters", "MPhil", "PhD"];
var degree_choice = ["My choice", "Family/Siblings/Others", "Both"];
var sources_of_information = ["Social Media", "IEC Student", "IEC Team Member", "Word of Mouth", "Email", "SMS", "Other"];
var type_of_employment = ["Part Time", "Full Time", "Not Employed"];
var age_groups = ["Under 18", "18-21", "22-24", "25-26", "27-30", "Above 30"];
var genders = ["male", "female", "other"];